=== Bakara11/AE-2/XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libros">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="libro" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo" type="xs:string" />
                    <xs:element name="indice" type="xs:string" />
                    <xs:element name="sinopsis" type="xs:string" />
                    <xs:element name="capitulo" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="contenido">
                            <xs:complexType>
                              <xs:attribute name="info" type="xs:string" use="required" />	
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="paginas" type="xs:integer" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" use="required" />
                  <xs:attribute name="tipo_clase">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="novela" />
                        <xs:enumeration value="infantil" />
                        <xs:enumeration value="didactico" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="paginas" type="xs:integer" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="periodicos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="periodico" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="indice" type="xs:string" />
                    <xs:element name="seccionp" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="articulo">  
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="contenido">
                                  <xs:complexType>
                                    <xs:attribute name="info" type="xs:string" use="required" />	
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="autor" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tipo" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="economia" />
                              <xs:enumeration value="opinion" />
                              <xs:enumeration value="deportes" />
                              <xs:enumeration value="nacional" />
                              <xs:enumeration value="internacional" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" use="required" />
                  <xs:attribute name="tipo_clase">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="nacional" />
                        <xs:enumeration value="internacional" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="fecha" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="revistas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="revista" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo" type="xs:string" />
                    <xs:element name="numero" type="xs:integer" />
                    <xs:element name="indice" type="xs:string" />
                    <xs:element name="seccionr" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="contenido">
                            <xs:complexType>
                              <xs:attribute name="info" type="xs:string" use="required" />	
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="paginas" type="xs:integer" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" use="required" />
                  <xs:attribute name="tipo_clase">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="informatica" />
                        <xs:enumeration value="corazon" />
                        <xs:enumeration value="coches" />
                        <xs:enumeration value="investigacion" />
                        <xs:enumeration value="otras" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="paginas" type="xs:integer" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Bakara11/AE-2/XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "XSD.xsd">
	<libros>
		<libro Id="L0001" tipo_clase="novela" paginas="680">
			<titulo>Dune</titulo>
			<indice>Capítulos</indice>
			<sinopsis>Arrakis y gusanos</sinopsis>
			<capitulo paginas="50">Capitulo 1
				<contenido info="L0001capitulo1.html">El comienzo</contenido>
			</capitulo>
			<capitulo paginas="33">Capitulo 2
				<contenido info="L0001capitulo2.html">Continúa…</contenido>
			</capitulo>
			<capitulo paginas="45">Capitulo 3
				<contenido info="L0001capitulo3.html">Continúa…</contenido>
			</capitulo>
		</libro>
		<libro Id="L0002" tipo_clase="didactico" paginas="340">
			<titulo>Una breve historia de casi todo</titulo>
			<indice>Capítulos</indice>
			<sinopsis>Divulgación científica</sinopsis>
			<capitulo paginas="25">Capitulo 1
				<contenido info="L0002capitulo1.html">El comienzo</contenido>
			</capitulo>
			<capitulo paginas="33">Capitulo 2
				<contenido info="L0002capitulo2.html">Continúa…</contenido>
			</capitulo>
			<capitulo paginas="29">Capitulo 3
				<contenido info="L0002capitulo3.html">Continúa…</contenido>
			</capitulo>
		</libro>
	</libros>
	<periodicos>
		<periodico Id="P0001" tipo_clase="nacional" fecha="20/05/22">
			<indice>Contenido</indice>
			<seccionp tipo="economia">
				<articulo autor="Mack Z.">
					<contenido info=" P0001sec1art1.html">Artículo 1</contenido>
				</articulo>
				<articulo autor="Steve J.">
					<contenido info=" P0001sec1art2.html"> Artículo 2</contenido>
				</articulo>
			</seccionp>
			<seccionp tipo="opinion">
				<articulo autor="Arturo P.">
					<contenido info=" P0001sec2art1.html">Artículo 1</contenido>
				</articulo>
				<articulo autor="Pedro S.">
					<contenido info=" P0001sec2art2.html">Artículo 2</contenido>
				</articulo>
			</seccionp>
		</periodico>
		<periodico Id="P0002" tipo_clase="internacional" fecha="21/05/22">
			<indice>Contenido</indice>
			<seccionp tipo="deportes">
				<articulo autor="Cristiano R.">
					<contenido info="P0002sec1art1.html">Artículo 1</contenido>
				</articulo>
				<articulo autor="Andrés I.">
					<contenido info=" P0002sec1art2.html"> Artículo 2</contenido>
				</articulo>
			</seccionp>
			<seccionp tipo="nacional">
				<articulo autor="Belén S.">
					<contenido info=" P0002sec2art1.html">Artículo 1</contenido>
				</articulo>
				<articulo autor="Antonio M.">
					<contenido info=" P0002sec2art2.html">Artículo 2</contenido>
				</articulo>
			</seccionp>
		</periodico>
	</periodicos>
	<revistas>
		<revista Id="R0001" tipo_clase="informatica" paginas="210">
			<titulo>PC hoy</titulo>
			<numero>1</numero>
			<indice>Contenido</indice>
			<seccionr paginas="20">
				<contenido info=" R0001parte1.html">Artículo 1</contenido>
			</seccionr>
			<seccionr paginas="15">
				<contenido info=" R0001parte2.html"> Artículo 2</contenido>
			</seccionr>
		</revista>
		<revista Id="R0002" tipo_clase="coches" paginas="180">
			<titulo>F1</titulo>
			<numero>6</numero>
			<indice>Contenido</indice>
			<seccionr paginas="22">
				<contenido info=" R0002parte1.html">Artículo 1</contenido>
			</seccionr>
			<seccionr paginas="5">
				<contenido info=" R0002parte2.html"> Artículo 2</contenido>
			</seccionr>
		</revista>
		<revista Id="R0003" tipo_clase="corazon" paginas="155">
			<titulo>Lecturas</titulo>
			<numero>3</numero>
			<indice>Contenido</indice>
			<seccionr paginas="12">
				<contenido info=" R0003parte1.html">Artículo 1</contenido>
			</seccionr>
			<seccionr paginas="17">
				<contenido info=" R0003parte2.html"> Artículo 2</contenido>
			</seccionr>
		</revista>
	</revistas>
</biblioteca>
